spring.application.name=gym-project
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always

# Info endpoint metadata
management.info.env.enabled=true
info.app.name=Gym Project
info.app.version=0.0.1-SNAPSHOT
info.app.description=Gym project


security.login.max-attempts=3
security.login.block-duration-seconds=30

jwt.secret=8f3Kx9LmQ2vP7sTzW4yN6aBcD1eFgHjK
jwt.expiration=3600000

# secret for service-to-service JWT
jwt.service.secret=s3rv1c3S3cr3tK3yF0rM1cr0s3rv1c3C0mm
jwt.service.expiration=86400000

report.service.name=gym-report-service

# Prometheus
management.prometheus.metrics.export.enabled=true

spring.profiles.active=local