spring.datasource.url=jdbc:postgresql://localhost:5432/gym_project_hiber?currentSchema=public
spring.datasource.username=postgres
spring.datasource.password=java

spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always

# Info endpoint metadata
management.info.env.enabled=true
info.app.name=Gym Project
info.app.version=0.0.1-SNAPSHOT
info.app.description=Gym project

# Prometheus
management.prometheus.metrics.export.enabled=true