data.trainee-file=classpath:data/trainees.json
data.trainer-file=classpath:data/trainers.json
data.training-file=classpath:data/trainings.json
data.trainingtype-file=classpath:data/trainingtypes.json
