# Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always

# Info endpoint metadata
management.info.env.enabled=true
info.app.name=Gym Project
info.app.version=0.0.1-SNAPSHOT
info.app.description=Gym project


security.login.max-attempts=3
security.login.block-duration-seconds=30

jwt.secret=8f3Kx9LmQ2vP7sTzW4yN6aBcD1eFgHjK
jwt.expiration=3600000

# Prometheus
management.prometheus.metrics.export.enabled=true

spring.profiles.active=local