spring.config.activate.on-profile=dev

spring.datasource.url=jdbc:postgresql://dev-db:5432/gym
spring.datasource.username=dev_user
spring.datasource.password=dev_pass

spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate