spring.config.activate.on-profile=standalone

eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

management.health.mongo.enabled=false
management.health.eureka.enabled=false