spring.application.name=gym-report-service
server.port=8081

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

jwt.service.secret=s3rv1c3S3cr3tK3yF0rM1cr0s3rv1c3C0mm
